const missions=[
 {title:"À l’intérieur de la cellule",sub:"Reconnaître les structures visibles",type:"qcm",question:"Quel élément contient l’information génétique et apparaît souvent comme une zone arrondie dans la cellule ?",options:["Le noyau","Le cytoplasme","La membrane plasmique","La matrice extracellulaire"],answer:0,explain:"Le noyau contient l’essentiel de l’information génétique. La membrane délimite la cellule et le cytoplasme occupe l’espace entre les deux.",image:"illustrations/cellule-elodee-sans-texte.webp"},
 {title:"Une cellule chlorophyllienne",sub:"Lire un dessin d’observation",type:"qcm",question:"Quel élément vert, caractéristique des cellules d’Élodée observées, réalise la photosynthèse ?",options:["Le chloroplaste","Le noyau","La paroi","La membrane plasmique"],answer:0,explain:"Les grains verts sont des chloroplastes contenant de la chlorophylle. Une cellule végétale possède aussi une paroi autour de la membrane.",image:"illustrations/cellule-elodee-sans-texte.webp"},
 {title:"Cellule ou tissu ?",sub:"Changer d’échelle d’organisation",type:"qcm",question:"Quelle définition d’un tissu est la plus juste ?",options:["Un ensemble organisé de cellules associées, avec une matrice extracellulaire éventuelle","Une très grande cellule possédant plusieurs noyaux","Un groupe d’organes ayant exactement la même fonction","Un ensemble de cellules obligatoirement identiques et directement accolées"],answer:0,explain:"Un tissu est un ensemble organisé de cellules. Celles-ci peuvent être séparées ou reliées par une matrice extracellulaire.",image:null},
 {title:"Le duel des cellules",sub:"Comparer sans confondre",type:"compare",question:"Quelle proposition compare correctement une bactérie et une cellule de muqueuse buccale ?",options:["La bactérie est généralement bien plus petite et ne possède pas de noyau.","La bactérie est plus petite, mais possède un noyau plus discret.","La cellule buccale est plus petite car elle ne possède pas de paroi."],answer:0,explain:"Les bactéries sont en général bien plus petites que les cellules animales et leur ADN n’est pas enfermé dans un noyau.",image:"illustrations/bacteries-cellule-buccale-v2.webp"},
 {title:"Déroule l’échelle",sub:"Manipuler avant de calculer",type:"scale",question:"Place le segment de 15 µm au début de la cellule, puis tire sur sa poignée jusqu’à l’autre extrémité. Combien de segments entiers entrent dans sa longueur ?",options:["Entre 7 et 8 segments","Entre 5 et 6 segments","Entre 8 et 9 segments","Entre 10 et 11 segments"],answer:0,explain:"On peut placer 7 segments complets, mais pas un huitième : la longueur correspond donc à un peu plus de 7 segments et à moins de 8.",image:"illustrations/elodee-estimation-interactive.webp",scaleReal:15,segmentFraction:.077,stretch:true,subject:"cellule d’Élodée"},
 {title:"Encadre la taille",sub:"Passer des segments aux micromètres",type:"qcm",question:"Le segment représente 15 µm. La cellule contient entre 7 et 8 segments. Quel intervalle de taille réelle peux-tu prévoir ?",options:["105 µm < taille < 120 µm","7 µm < taille < 8 µm","15 µm < taille < 105 µm","120 µm < taille < 135 µm"],answer:0,explain:"7 × 15 = 105 µm et 8 × 15 = 120 µm. Le résultat précis devra obligatoirement être compris entre ces deux valeurs.",image:null},
 {title:"La taille précise",sub:"Mesurer, diviser puis multiplier",type:"calc",question:"Le dessin mesure 12,2 cm. Le segment de 15 µm mesure 1,6 cm sur ce même dessin. Calcule la taille réelle de la cellule. La valeur exacte ou sa valeur arrondie au dixième sont acceptées.",answer:114.375,roundedAnswer:114.4,drawSize:12.2,scaleDraw:1.6,scaleReal:15,explain:"12,2 ÷ 1,6 = 7,625 segments, puis 7,625 × 15 = 114,375 µm, soit environ 114,4 µm.",image:"illustrations/methode-division.webp"},
 {title:"Le sens du micromètre",sub:"Calculer un ordre de grandeur",type:"qcm",question:"Dix feuilles empilées mesurent environ 1 mm, soit 1 000 µm. Combien de cellules de 114,4 µm faudrait-il aligner pour atteindre environ 1 mm ?",options:["Environ 8,7 cellules","Environ 1,1 cellule","Environ 11,4 cellules","Environ 87 cellules"],answer:0,explain:"1 000 ÷ 114,4 ≈ 8,7. Il faudrait donc presque 9 cellules alignées pour atteindre 1 mm.",image:"illustrations/repere-micrometre.webp"},
 {title:"Une échelle plus grande",sub:"Comparer avant de calculer",type:"scale",question:"Glisse le segment de 2 µm le long de la bactérie. Que peux-tu conclure ?",options:["La bactérie est plus petite que le segment, mais dépasse sa moitié","La bactérie contient entre 1 et 2 segments entiers","La bactérie est exactement deux fois plus longue que le segment","La bactérie est plus petite que la moitié du segment"],answer:0,explain:"Le segment entier est plus long que la bactérie, mais sa moitié est plus courte : la bactérie mesure donc entre 0,5 et 1 segment.",image:"illustrations/bacterie-mesure.webp",scaleReal:2,segmentFraction:.60,stretch:false,subject:"bactérie"},
 {title:"Encadre la bactérie",sub:"Passer aux micromètres",type:"qcm",question:"La bactérie mesure entre 0,5 et 1 segment, et un segment représente 2 µm. Quel est son intervalle de taille ?",options:["1 µm < taille < 2 µm","0,5 µm < taille < 1 µm","2 µm < taille < 4 µm","0 µm < taille < 0,5 µm"],answer:0,explain:"0,5 × 2 = 1 µm et 1 × 2 = 2 µm. La bactérie mesure donc entre 1 et 2 µm."},
 {title:"La taille de la bactérie",sub:"Appliquer la méthode complète",type:"calc",question:"Sur le document, la bactérie mesure 3,5 cm et le segment représentant 2 µm mesure 5 cm. Calcule la taille réelle de la bactérie. La valeur exacte ou son arrondi au dixième sont acceptés.",answer:1.4,roundedAnswer:1.4,drawSize:3.5,scaleDraw:5,scaleReal:2,explain:"3,5 ÷ 5 = 0,7 segment, puis 0,7 × 2 = 1,4 µm. Le résultat appartient bien à l’intervalle prévu entre 1 et 2 µm.",image:"illustrations/bacterie-mesure.webp"}
];
let current=0,score=0,locked=false,currentAnswer=0;
const $=s=>document.querySelector(s), screens=["#homeScreen","#gameScreen","#resultScreen"];
function show(id){screens.forEach(s=>$(s).classList.toggle("active",s===id));$("#hud").classList.toggle("hidden",id!=="#gameScreen")}
function start(){current=0;score=0;locked=false;$("#score").textContent=0;show("#gameScreen");render()}
function head(m){return `<div class="mission-head"><div class="mission-num">${current+1}</div><div><span class="eyebrow">Mission ${current+1} sur ${missions.length}</span><h1>${m.title}</h1><p>${m.sub}</p></div></div>`}
function image(m){return m.image?`<div class="image-panel"><img src="${m.image}" alt="Support d'observation pour la question"></div>`:""}
function scaleLab(m){return `<div class="scale-lab"><div class="cell-stage" id="cellStage"><img src="${m.image}" alt="Support de mesure : ${m.subject}"><div class="scale-tape${m.stretch?"":" fixed"}" id="scaleTape" aria-label="Segment d’échelle déplaçable"><span class="tape-value">${m.scaleReal} µm</span>${m.stretch?'<b class="tape-handle" id="tapeHandle" title="Tirer pour dérouler"></b>':""}</div></div><div class="scale-help"><span>↔️ ${m.stretch?"Glisse le segment bleu, puis tire sur la poignée orange.":"Glisse le segment bleu pour le comparer à la bactérie."}</span><button class="secondary mini" id="resetTape" type="button">Recommencer</button></div></div>`}
function shuffledOptions(m){const choices=m.options.map((text,index)=>({text,correct:index===m.answer}));for(let i=choices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]]}currentAnswer=choices.findIndex(choice=>choice.correct);return choices}
function render(){locked=false;const m=missions[current];$("#missionLabel").textContent=`Mission ${current+1}/${missions.length}`;$("#progressBar").style.width=`${current/missions.length*100}%`;let body=head(m)+(m.type==="scale"?scaleLab(m):image(m))+`<div class="question">${m.question}</div>`;
 if(m.type==="qcm"||m.type==="compare"||m.type==="scale"){const choices=shuffledOptions(m);body+=`<div class="${m.type==="compare"?"compare":"options"}">${choices.map((choice,i)=>`<button class="option" data-i="${i}">${choice.text}</button>`).join("")}</div>`}
 if(m.type==="calc") body+=`<div class="formula"><input id="drawSize" value="${String(m.drawSize).replace('.',',')}" readonly aria-label="Longueur du dessin"><span>÷</span><input id="scaleDraw" value="${String(m.scaleDraw).replace('.',',')}" readonly aria-label="Longueur dessinée du segment"><span>× ${String(m.scaleReal).replace('.',',')} µm =</span><input id="calcAnswer" inputmode="decimal" autocomplete="off" placeholder="Réponse en µm" aria-label="Taille réelle en micromètres"><button class="primary" id="calcBtn">Vérifier</button></div>`;
 body+=`<div class="feedback" id="feedback"></div><div class="actions"><button class="primary hidden" id="nextBtn">${current===missions.length-1?"Voir mon résultat":"Mission suivante →"}</button></div>`;$("#missionCard").innerHTML=body;
 document.querySelectorAll(".option").forEach(b=>b.onclick=()=>answerOption(+b.dataset.i));if(m.type==="scale")initScaleLab(m);if(m.type==="calc"){$("#calcBtn").onclick=answerCalc;$("#calcAnswer").onkeydown=e=>{if(e.key==="Enter")answerCalc()};$("#calcAnswer").focus()}$("#nextBtn").onclick=next;window.scrollTo({top:0,behavior:"smooth"});}
function initScaleLab(m){const stage=$("#cellStage"),tape=$("#scaleTape"),handle=$("#tapeHandle");let action=null,startX=0,startY=0,startLeft=0,startTop=0,startWidth=0,segment=0;const reset=()=>{segment=stage.clientWidth*m.segmentFraction;tape.style.setProperty("--segment",`${segment}px`);tape.style.width=`${segment}px`;tape.style.left="3%";tape.style.top="78%"};const down=(e,mode)=>{e.preventDefault();action=mode;startX=e.clientX;startY=e.clientY;startLeft=tape.offsetLeft;startTop=tape.offsetTop;startWidth=tape.offsetWidth;tape.setPointerCapture(e.pointerId)};tape.onpointerdown=e=>{if(e.target!==handle)down(e,"move")};if(handle)handle.onpointerdown=e=>down(e,"resize");tape.onpointermove=e=>{if(!action)return;if(action==="resize"){const max=stage.clientWidth-tape.offsetLeft-5;tape.style.width=`${Math.max(segment,Math.min(max,startWidth+e.clientX-startX))}px`}else{const left=Math.max(0,Math.min(stage.clientWidth-tape.offsetWidth,startLeft+e.clientX-startX));const top=Math.max(0,Math.min(stage.clientHeight-tape.offsetHeight,startTop+e.clientY-startY));tape.style.left=`${left}px`;tape.style.top=`${top}px`}};tape.onpointerup=tape.onpointercancel=()=>action=null;$("#resetTape").onclick=reset;reset()}
function answerOption(i){if(locked)return;const m=missions[current];locked=true;document.querySelectorAll(".option").forEach((b,j)=>{b.disabled=true;if(j===currentAnswer)b.classList.add("good");if(j===i&&i!==currentAnswer)b.classList.add("bad")});finish(i===currentAnswer,m.explain)}
function n(v){return parseFloat(v.trim().replace(",","."))}
function answerCalc(){if(locked)return;const m=missions[current],raw=$("#calcAnswer").value.trim().replace(",","."),c=parseFloat(raw);if(Number.isNaN(c)){toast("Saisis ton résultat dans la dernière case.");return}locked=true;const decimals=(raw.split(".")[1]||"").length,exact=Math.abs(c-m.answer)<.0005,rounded=decimals===1&&Math.abs(c-m.roundedAnswer)<.0005,ok=exact||rounded;["#drawSize","#scaleDraw","#calcAnswer"].forEach(s=>$(s).disabled=true);$("#calcBtn").disabled=true;finish(ok,m.explain+(ok?"":" Reprends : longueur de l’objet ÷ longueur du segment × valeur réelle du segment."))}
function finish(ok,text){if(ok){score+=100;$("#score").textContent=score}$("#feedback").innerHTML=`<b>${ok?"✓ Bien vu !":"✗ Pas tout à fait."}</b> ${text}`;$("#feedback").style.background=ok?"#e6faef":"#fff1ed";$("#nextBtn").classList.remove("hidden")}
function next(){current++;if(current<missions.length)render();else result()}
function result(){show("#resultScreen");$("#finalScore").textContent=score;$("#progressBar").style.width="100%";let title,text,badge;if(score>=900){title="Expert du microscope";text="Tu sais relier observation, ordre de grandeur et calcul d’échelle. L’échantillon n’a plus de secret pour toi.";badge="🏆"}else if(score>=650){title="Explorateur confirmé";text="Les bases sont solides. Rejoue une fois pour verrouiller la méthode de calcul et le vocabulaire.";badge="🔬"}else{title="Apprenti observateur";text="Tu progresses. Relis les corrections, puis retente les missions : elles changent vite de difficulté quand la méthode est comprise.";badge="🌱"}$("#resultTitle").textContent=title;$("#resultText").textContent=text;$("#resultBadge").textContent=badge;$("#recap").classList.add("hidden")}
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
$("#startBtn").onclick=start;$("#retryBtn").onclick=start;$("#reviewBtn").onclick=()=>$("#recap").classList.toggle("hidden");$("#homeBtn").onclick=()=>show("#homeScreen");
